baseURL = 'https://konflux-ci.dev/'
languageCode = 'en-us'
title = 'Konflux'
theme = ['konflux', 'github.com/devcows/hugo-universal-theme']

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[params]
    disabled_logo = false
    logo_text = "Konflux"

    logo = "img/logo.svg"
    logo_small = "img/logo.svg"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

[[menu.main]]
    name       = "User Guide"
    identifier = "menu.userguide"
    url        = "https://konflux-ci.dev/docs"
    weight     = 2

[[menu.arch]]
    name       = "Architecture"
    identifier = "menu.architecture"
    url        = "https://konflux-ci.dev/architecture"
    weight     = 2

[[menu.community]]
    name       = "Community"
    identifier = "menu.community"
    url        = "https://github.com/konflux-ci/community/?tab=readme-ov-file#welcome-to-the-konflux-community"
    weight     = 2

[[menu.support]]
    name       = "Support"
    identifier = "menu.support"
    url        = "https://github.com/konflux-ci/support/"
    weight     = 2

[params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
